-- Idempotent input seed for the source-backed review graph E2E path.
--
-- This does not insert review_challenge_packets directly. It only plants the
-- vetted crawler rows needed for backfillReviewChallengePackets.ts to fetch,
-- decompose, and persist a real GitHub PR into the living context graph.

INSERT OR REPLACE INTO qualified_repos (
  id,
  github_url,
  full_name,
  description,
  homepage,
  primary_language,
  license_spdx,
  stars,
  last_pushed_at,
  is_archived,
  is_fork,
  sloc,
  file_count,
  mean_ccn,
  has_ci,
  has_tests,
  test_framework,
  seniority_band,
  detected_domain,
  domain_confidence,
  pr_quality_score,
  contamination_risk,
  detected_stack_json,
  pass,
  disqualified,
  disqualified_reason,
  crawled_at,
  refreshed_at,
  open_pr_count,
  open_feature_issue_count,
  business_logic_ratio,
  cross_module_change_rate,
  admin_status,
  admin_reason,
  readme_excerpt,
  root_tree_json
) VALUES (
  973,
  'https://github.com/mui/base-ui',
  'mui/base-ui',
  'Base UI is a headless React component library with source-backed pull requests suitable for review graph decomposition.',
  'https://base-ui.com',
  'TypeScript',
  'MIT',
  10000,
  '2026-06-01T00:00:00Z',
  0,
  0,
  NULL,
  NULL,
  NULL,
  1,
  1,
  'vitest',
  'senior',
  'frontend-ui',
  0.95,
  1,
  0,
  '["typescript","react","vitest","playwright"]',
  2,
  0,
  NULL,
  '2026-06-24T00:00:00Z',
  '2026-06-24T00:00:00Z',
  NULL,
  NULL,
  NULL,
  NULL,
  'approved',
  'Seeded for live source-backed review graph E2E packet decomposition.',
  'Headless React UI primitives used to build accessible component behavior.',
  '["packages","src","test","package.json"]'
);

INSERT INTO repo_sample_prs (
  repo_id,
  pr_number,
  pr_url,
  title,
  merged_at,
  resolves_issue_number,
  changed_file_count,
  modifies_tests,
  additions,
  deletions,
  construct_slugs_json,
  swe_bench_eligible,
  changed_file_paths_json,
  pr_narrative,
  pr_narrative_embedding_json,
  pr_narrative_version
) VALUES (
  973,
  973,
  'https://github.com/mui/base-ui/pull/973',
  '[popover] Better handle impatient clicks',
  '2026-06-01T00:00:00Z',
  NULL,
  3,
  1,
  NULL,
  NULL,
  '["react","popover","click-handling","tests"]',
  1,
  '["packages/react/src/popover/root/usePopoverRoot.ts","packages/react/src/popover/trigger/PopoverTrigger.tsx","packages/react/src/popover/root/usePopoverRoot.test.tsx"]',
  'The PR changes popover trigger click handling by adding a patient click threshold for impatient clicks and updating tests around popover behavior.',
  NULL,
  'source-backed-e2e-v1'
)
ON CONFLICT(repo_id, pr_number) DO UPDATE SET
  pr_url = excluded.pr_url,
  title = excluded.title,
  merged_at = excluded.merged_at,
  resolves_issue_number = excluded.resolves_issue_number,
  changed_file_count = excluded.changed_file_count,
  modifies_tests = excluded.modifies_tests,
  additions = excluded.additions,
  deletions = excluded.deletions,
  construct_slugs_json = excluded.construct_slugs_json,
  swe_bench_eligible = excluded.swe_bench_eligible,
  changed_file_paths_json = excluded.changed_file_paths_json,
  pr_narrative = excluded.pr_narrative,
  pr_narrative_embedding_json = excluded.pr_narrative_embedding_json,
  pr_narrative_version = excluded.pr_narrative_version;
