-- Idempotent input seed for the source-backed review graph E2E path.
--
-- This does not insert review_challenge_packets directly. It only plants the
-- vetted crawler rows needed for backfillReviewChallengePackets.ts to fetch,
-- decompose, and persist a real GitHub PR into the living context graph.

INSERT INTO qualified_repos (
  github_url,
  full_name,
  description,
  homepage,
  primary_language,
  license_spdx,
  stars,
  last_pushed_at,
  is_archived,
  is_fork,
  sloc,
  file_count,
  mean_ccn,
  has_ci,
  has_tests,
  test_framework,
  seniority_band,
  detected_domain,
  domain_confidence,
  pr_quality_score,
  contamination_risk,
  detected_stack_json,
  pass,
  disqualified,
  disqualified_reason,
  crawled_at,
  refreshed_at,
  open_pr_count,
  open_feature_issue_count,
  business_logic_ratio,
  cross_module_change_rate,
  admin_status,
  admin_reason,
  readme_excerpt,
  root_tree_json
) VALUES (
  'https://github.com/mui/base-ui',
  'mui/base-ui',
  'Base UI is a headless React component library with source-backed pull requests suitable for review graph decomposition.',
  'https://base-ui.com',
  'TypeScript',
  'MIT',
  10000,
  '2026-06-01T00:00:00Z',
  0,
  0,
  NULL,
  NULL,
  NULL,
  1,
  1,
  'vitest',
  'senior',
  'frontend-ui',
  0.95,
  1,
  0,
  '["typescript","react","vitest","playwright"]',
  2,
  0,
  NULL,
  '2026-06-24T00:00:00Z',
  '2026-06-24T00:00:00Z',
  NULL,
  NULL,
  NULL,
  NULL,
  'approved',
  'Seeded for live source-backed review graph E2E packet decomposition.',
  'Headless React UI primitives used to build accessible component behavior.',
  '["packages","src","test","package.json"]'
)
ON CONFLICT(github_url) DO UPDATE SET
  full_name = excluded.full_name,
  description = excluded.description,
  homepage = excluded.homepage,
  primary_language = excluded.primary_language,
  license_spdx = excluded.license_spdx,
  stars = excluded.stars,
  last_pushed_at = excluded.last_pushed_at,
  is_archived = excluded.is_archived,
  is_fork = excluded.is_fork,
  has_ci = excluded.has_ci,
  has_tests = excluded.has_tests,
  test_framework = excluded.test_framework,
  seniority_band = excluded.seniority_band,
  detected_domain = excluded.detected_domain,
  domain_confidence = excluded.domain_confidence,
  pr_quality_score = excluded.pr_quality_score,
  contamination_risk = excluded.contamination_risk,
  detected_stack_json = excluded.detected_stack_json,
  pass = excluded.pass,
  disqualified = excluded.disqualified,
  disqualified_reason = excluded.disqualified_reason,
  refreshed_at = excluded.refreshed_at,
  admin_status = excluded.admin_status,
  admin_reason = excluded.admin_reason,
  readme_excerpt = excluded.readme_excerpt,
  root_tree_json = excluded.root_tree_json;

INSERT INTO repo_sample_prs (
  repo_id,
  pr_number,
  pr_url,
  title,
  merged_at,
  resolves_issue_number,
  changed_file_count,
  modifies_tests,
  additions,
  deletions,
  construct_slugs_json,
  swe_bench_eligible,
  changed_file_paths_json,
  pr_narrative,
  pr_narrative_embedding_json,
  pr_narrative_version
) VALUES (
  (SELECT id FROM qualified_repos WHERE github_url = 'https://github.com/mui/base-ui'),
  973,
  'https://github.com/mui/base-ui/pull/973',
  '[popover] Better handle impatient clicks',
  '2026-06-01T00:00:00Z',
  NULL,
  3,
  1,
  NULL,
  NULL,
  '["react","popover","click-handling","tests"]',
  1,
  '["packages/react/src/popover/root/usePopoverRoot.ts","packages/react/src/popover/trigger/PopoverTrigger.tsx","packages/react/src/popover/root/usePopoverRoot.test.tsx"]',
  'The PR changes popover trigger click handling by adding a patient click threshold for impatient clicks and updating tests around popover behavior.',
  NULL,
  'source-backed-e2e-v1'
)
ON CONFLICT(repo_id, pr_number) DO UPDATE SET
  pr_url = excluded.pr_url,
  title = excluded.title,
  merged_at = excluded.merged_at,
  resolves_issue_number = excluded.resolves_issue_number,
  changed_file_count = excluded.changed_file_count,
  modifies_tests = excluded.modifies_tests,
  additions = excluded.additions,
  deletions = excluded.deletions,
  construct_slugs_json = excluded.construct_slugs_json,
  swe_bench_eligible = excluded.swe_bench_eligible,
  changed_file_paths_json = excluded.changed_file_paths_json,
  pr_narrative = excluded.pr_narrative,
  pr_narrative_embedding_json = excluded.pr_narrative_embedding_json,
  pr_narrative_version = excluded.pr_narrative_version;

-- Third real repo candidate used to prove CODE_REVIEW inventory breadth beyond
-- Base UI and Workers SDK. The packet builder dry-runs these PRs as
-- production-ready with complete provenance, code changes, and regression tests.
INSERT INTO qualified_repos (
  github_url,
  full_name,
  description,
  homepage,
  primary_language,
  license_spdx,
  stars,
  last_pushed_at,
  is_archived,
  is_fork,
  sloc,
  file_count,
  mean_ccn,
  has_ci,
  has_tests,
  test_framework,
  seniority_band,
  detected_domain,
  domain_confidence,
  pr_quality_score,
  contamination_risk,
  detected_stack_json,
  pass,
  disqualified,
  disqualified_reason,
  crawled_at,
  refreshed_at,
  open_pr_count,
  open_feature_issue_count,
  business_logic_ratio,
  cross_module_change_rate,
  admin_status,
  admin_reason,
  readme_excerpt,
  root_tree_json
) VALUES (
  'https://github.com/vercel/swr',
  'vercel/swr',
  'React Hooks for Data Fetching with source-backed pull requests suitable for CODE_REVIEW packet decomposition.',
  'https://swr.vercel.app',
  'TypeScript',
  'MIT',
  32420,
  '2026-07-02T14:44:21Z',
  0,
  0,
  NULL,
  NULL,
  NULL,
  1,
  1,
  'jest',
  'senior',
  'frontend-data-fetching',
  0.95,
  1,
  0,
  '["typescript","react","hooks","suspense","cache","data-fetching","jest","e2e"]',
  2,
  0,
  NULL,
  '2026-07-02T14:44:21Z',
  '2026-07-02T14:44:21Z',
  NULL,
  NULL,
  NULL,
  NULL,
  'approved',
  'Seeded for live source-backed review graph inventory breadth proof.',
  'SWR is a React Hooks data-fetching library covering cache, Suspense, hydration, prefetching, and stale-while-revalidate behavior.',
  '["src","test","e2e","package.json"]'
)
ON CONFLICT(github_url) DO UPDATE SET
  full_name = excluded.full_name,
  description = excluded.description,
  homepage = excluded.homepage,
  primary_language = excluded.primary_language,
  license_spdx = excluded.license_spdx,
  stars = excluded.stars,
  last_pushed_at = excluded.last_pushed_at,
  is_archived = excluded.is_archived,
  is_fork = excluded.is_fork,
  has_ci = excluded.has_ci,
  has_tests = excluded.has_tests,
  test_framework = excluded.test_framework,
  seniority_band = excluded.seniority_band,
  detected_domain = excluded.detected_domain,
  domain_confidence = excluded.domain_confidence,
  pr_quality_score = excluded.pr_quality_score,
  contamination_risk = excluded.contamination_risk,
  detected_stack_json = excluded.detected_stack_json,
  pass = excluded.pass,
  disqualified = excluded.disqualified,
  disqualified_reason = excluded.disqualified_reason,
  refreshed_at = excluded.refreshed_at,
  admin_status = excluded.admin_status,
  admin_reason = excluded.admin_reason,
  readme_excerpt = excluded.readme_excerpt,
  root_tree_json = excluded.root_tree_json;

INSERT INTO repo_sample_prs (
  repo_id,
  pr_number,
  pr_url,
  title,
  merged_at,
  resolves_issue_number,
  changed_file_count,
  modifies_tests,
  additions,
  deletions,
  construct_slugs_json,
  swe_bench_eligible,
  changed_file_paths_json,
  pr_narrative,
  pr_narrative_embedding_json,
  pr_narrative_version
) VALUES (
  (SELECT id FROM qualified_repos WHERE github_url = 'https://github.com/vercel/swr'),
  4212,
  'https://github.com/vercel/swr/pull/4212',
  'fix: isHydration will cause unnecessary rerender',
  '2026-01-30T17:55:26Z',
  NULL,
  6,
  1,
  115,
  11,
  '["react","swr","hydration","render-count","prefetch","tests"]',
  1,
  '["e2e/site/app/render-count/page.tsx","e2e/site/app/server-prefetch-warning/page.tsx","e2e/test/initial-render.test.ts","e2e/test/server-prefetch-warning.test.ts","src/index/use-swr.ts","test/use-swr-server.test.tsx"]',
  'The PR fixes unnecessary SWR rerenders around hydration and server prefetch behavior, adding e2e pages plus regression tests for initial render counts and prefetch warnings.',
  NULL,
  'source-backed-e2e-v1'
)
ON CONFLICT(repo_id, pr_number) DO UPDATE SET
  pr_url = excluded.pr_url,
  title = excluded.title,
  merged_at = excluded.merged_at,
  resolves_issue_number = excluded.resolves_issue_number,
  changed_file_count = excluded.changed_file_count,
  modifies_tests = excluded.modifies_tests,
  additions = excluded.additions,
  deletions = excluded.deletions,
  construct_slugs_json = excluded.construct_slugs_json,
  swe_bench_eligible = excluded.swe_bench_eligible,
  changed_file_paths_json = excluded.changed_file_paths_json,
  pr_narrative = excluded.pr_narrative,
  pr_narrative_embedding_json = excluded.pr_narrative_embedding_json,
  pr_narrative_version = excluded.pr_narrative_version;

INSERT INTO repo_sample_prs (
  repo_id,
  pr_number,
  pr_url,
  title,
  merged_at,
  resolves_issue_number,
  changed_file_count,
  modifies_tests,
  additions,
  deletions,
  construct_slugs_json,
  swe_bench_eligible,
  changed_file_paths_json,
  pr_narrative,
  pr_narrative_embedding_json,
  pr_narrative_version
) VALUES (
  (SELECT id FROM qualified_repos WHERE github_url = 'https://github.com/vercel/swr'),
  4271,
  'https://github.com/vercel/swr/pull/4271',
  'Prevent resolved promise to suspend due to missing status',
  '2026-06-19T17:23:43Z',
  NULL,
  3,
  1,
  77,
  1,
  '["react","swr","suspense","resolved-promise","server-rendering","tests"]',
  1,
  '["src/index/use-swr.ts","test/use-swr-server.test.tsx","test/use-swr-suspense.test.tsx"]',
  'The PR prevents resolved promises from entering Suspense because of missing status metadata, with server and suspense regression tests around useSWR behavior.',
  NULL,
  'source-backed-e2e-v1'
)
ON CONFLICT(repo_id, pr_number) DO UPDATE SET
  pr_url = excluded.pr_url,
  title = excluded.title,
  merged_at = excluded.merged_at,
  resolves_issue_number = excluded.resolves_issue_number,
  changed_file_count = excluded.changed_file_count,
  modifies_tests = excluded.modifies_tests,
  additions = excluded.additions,
  deletions = excluded.deletions,
  construct_slugs_json = excluded.construct_slugs_json,
  swe_bench_eligible = excluded.swe_bench_eligible,
  changed_file_paths_json = excluded.changed_file_paths_json,
  pr_narrative = excluded.pr_narrative,
  pr_narrative_embedding_json = excluded.pr_narrative_embedding_json,
  pr_narrative_version = excluded.pr_narrative_version;

INSERT INTO repo_sample_prs (
  repo_id,
  pr_number,
  pr_url,
  title,
  merged_at,
  resolves_issue_number,
  changed_file_count,
  modifies_tests,
  additions,
  deletions,
  construct_slugs_json,
  swe_bench_eligible,
  changed_file_paths_json,
  pr_narrative,
  pr_narrative_embedding_json,
  pr_narrative_version
) VALUES (
  (SELECT id FROM qualified_repos WHERE github_url = 'https://github.com/mui/base-ui'),
  5110,
  'https://github.com/mui/base-ui/pull/5110',
  '[popups] Fix rendered trigger id ownership',
  '2026-06-24T11:46:32Z',
  5108,
  4,
  1,
  165,
  12,
  '["react","popup","trigger","aria","tests"]',
  1,
  '["packages/react/src/tooltip/root/TooltipRoot.detached-triggers.test.tsx","packages/react/src/tooltip/trigger/TooltipTrigger.test.tsx","packages/react/src/utils/popups/popupStoreUtils.test.tsx","packages/react/src/utils/popups/popupStoreUtils.ts"]',
  'The PR fixes rendered popup trigger id ownership for Base UI popup families, covering Tooltip, Preview Card, Popover, Menu, and Dialog trigger state/ARIA behavior with tests.',
  NULL,
  'source-backed-e2e-v1'
)
ON CONFLICT(repo_id, pr_number) DO UPDATE SET
  pr_url = excluded.pr_url,
  title = excluded.title,
  merged_at = excluded.merged_at,
  resolves_issue_number = excluded.resolves_issue_number,
  changed_file_count = excluded.changed_file_count,
  modifies_tests = excluded.modifies_tests,
  additions = excluded.additions,
  deletions = excluded.deletions,
  construct_slugs_json = excluded.construct_slugs_json,
  swe_bench_eligible = excluded.swe_bench_eligible,
  changed_file_paths_json = excluded.changed_file_paths_json,
  pr_narrative = excluded.pr_narrative,
  pr_narrative_embedding_json = excluded.pr_narrative_embedding_json,
  pr_narrative_version = excluded.pr_narrative_version;

INSERT INTO repo_sample_prs (
  repo_id,
  pr_number,
  pr_url,
  title,
  merged_at,
  resolves_issue_number,
  changed_file_count,
  modifies_tests,
  additions,
  deletions,
  construct_slugs_json,
  swe_bench_eligible,
  changed_file_paths_json,
  pr_narrative,
  pr_narrative_embedding_json,
  pr_narrative_version
) VALUES (
  (SELECT id FROM qualified_repos WHERE github_url = 'https://github.com/mui/base-ui'),
  5095,
  'https://github.com/mui/base-ui/pull/5095',
  '[progress] Fix custom min/max semantics to match the indicator',
  '2026-06-22T11:19:36Z',
  NULL,
  5,
  1,
  122,
  31,
  '["react","progress","min-max","indicator","tests"]',
  1,
  '["packages/react/src/progress/indicator/ProgressIndicator.tsx","packages/react/src/progress/root/ProgressRoot.test.tsx","packages/react/src/progress/root/ProgressRoot.tsx","packages/react/src/progress/root/ProgressRootContext.tsx","packages/react/src/utils/formatNumber.ts"]',
  'The PR fixes Progress root custom min/max semantics, aligns indicator behavior with formatted values, and adds regression coverage around progress calculations.',
  NULL,
  'source-backed-e2e-v1'
)
ON CONFLICT(repo_id, pr_number) DO UPDATE SET
  pr_url = excluded.pr_url,
  title = excluded.title,
  merged_at = excluded.merged_at,
  resolves_issue_number = excluded.resolves_issue_number,
  changed_file_count = excluded.changed_file_count,
  modifies_tests = excluded.modifies_tests,
  additions = excluded.additions,
  deletions = excluded.deletions,
  construct_slugs_json = excluded.construct_slugs_json,
  swe_bench_eligible = excluded.swe_bench_eligible,
  changed_file_paths_json = excluded.changed_file_paths_json,
  pr_narrative = excluded.pr_narrative,
  pr_narrative_embedding_json = excluded.pr_narrative_embedding_json,
  pr_narrative_version = excluded.pr_narrative_version;

-- Second real packet candidate used to prove automatic matching can measure
-- contrast separation rather than selecting from a one-packet corpus.
INSERT INTO qualified_repos (
  github_url,
  full_name,
  description,
  homepage,
  primary_language,
  license_spdx,
  stars,
  last_pushed_at,
  is_archived,
  is_fork,
  sloc,
  file_count,
  mean_ccn,
  has_ci,
  has_tests,
  test_framework,
  seniority_band,
  detected_domain,
  domain_confidence,
  pr_quality_score,
  contamination_risk,
  detected_stack_json,
  pass,
  disqualified,
  disqualified_reason,
  crawled_at,
  refreshed_at,
  open_pr_count,
  open_feature_issue_count,
  business_logic_ratio,
  cross_module_change_rate,
  admin_status,
  admin_reason,
  readme_excerpt,
  root_tree_json
) VALUES (
  'https://github.com/cloudflare/workers-sdk',
  'cloudflare/workers-sdk',
  'Cloudflare Workers SDK and Wrangler source repository with source-backed pull requests suitable for review graph decomposition.',
  NULL,
  'TypeScript',
  'NOASSERTION',
  0,
  '2026-06-26T10:51:43Z',
  0,
  0,
  NULL,
  NULL,
  NULL,
  1,
  1,
  'vitest',
  'senior',
  'developer-tooling',
  0.95,
  1,
  0,
  '["typescript","wrangler","vitest","cloudflare-workers","workflows"]',
  2,
  0,
  NULL,
  '2026-06-26T10:51:43Z',
  '2026-06-26T10:51:43Z',
  NULL,
  NULL,
  NULL,
  NULL,
  'approved',
  'Seeded for live source-backed review graph contrast proof.',
  'Cloudflare Workers SDK and Wrangler tooling for building, testing, and deploying Workers applications.',
  '["packages","fixtures","templates","package.json"]'
)
ON CONFLICT(github_url) DO UPDATE SET
  full_name = excluded.full_name,
  description = excluded.description,
  homepage = excluded.homepage,
  primary_language = excluded.primary_language,
  license_spdx = excluded.license_spdx,
  stars = excluded.stars,
  last_pushed_at = excluded.last_pushed_at,
  is_archived = excluded.is_archived,
  is_fork = excluded.is_fork,
  has_ci = excluded.has_ci,
  has_tests = excluded.has_tests,
  test_framework = excluded.test_framework,
  seniority_band = excluded.seniority_band,
  detected_domain = excluded.detected_domain,
  domain_confidence = excluded.domain_confidence,
  pr_quality_score = excluded.pr_quality_score,
  contamination_risk = excluded.contamination_risk,
  detected_stack_json = excluded.detected_stack_json,
  pass = excluded.pass,
  disqualified = excluded.disqualified,
  disqualified_reason = excluded.disqualified_reason,
  refreshed_at = excluded.refreshed_at,
  admin_status = excluded.admin_status,
  admin_reason = excluded.admin_reason,
  readme_excerpt = excluded.readme_excerpt,
  root_tree_json = excluded.root_tree_json;

INSERT INTO repo_sample_prs (
  repo_id,
  pr_number,
  pr_url,
  title,
  merged_at,
  resolves_issue_number,
  changed_file_count,
  modifies_tests,
  additions,
  deletions,
  construct_slugs_json,
  swe_bench_eligible,
  changed_file_paths_json,
  pr_narrative,
  pr_narrative_embedding_json,
  pr_narrative_version
) VALUES (
  (SELECT id FROM qualified_repos WHERE github_url = 'https://github.com/cloudflare/workers-sdk'),
  14118,
  'https://github.com/cloudflare/workers-sdk/pull/14118',
  '[workflows-shared] Fix Uint8Array step outputs dragging backing ArrayBuffer in local Workflows',
  '2026-06-18T15:18:00Z',
  NULL,
  3,
  1,
  331,
  1,
  '["typescript","workflows","uint8array","arraybuffer","local-dev","tests"]',
  1,
  '[".changeset/fix-workflows-uint8array-step-output.md","packages/workflows-shared/src/context.ts","packages/workflows-shared/tests/context.test.ts"]',
  'The PR fixes local Workflows Uint8Array step output persistence so sliced typed-array views do not drag oversized backing ArrayBuffers into storage, with regression tests for tight and offset buffers.',
  NULL,
  'source-backed-e2e-v1'
)
ON CONFLICT(repo_id, pr_number) DO UPDATE SET
  pr_url = excluded.pr_url,
  title = excluded.title,
  merged_at = excluded.merged_at,
  resolves_issue_number = excluded.resolves_issue_number,
  changed_file_count = excluded.changed_file_count,
  modifies_tests = excluded.modifies_tests,
  additions = excluded.additions,
  deletions = excluded.deletions,
  construct_slugs_json = excluded.construct_slugs_json,
  swe_bench_eligible = excluded.swe_bench_eligible,
  changed_file_paths_json = excluded.changed_file_paths_json,
  pr_narrative = excluded.pr_narrative,
  pr_narrative_embedding_json = excluded.pr_narrative_embedding_json,
  pr_narrative_version = excluded.pr_narrative_version;

INSERT INTO repo_sample_prs (
  repo_id,
  pr_number,
  pr_url,
  title,
  merged_at,
  resolves_issue_number,
  changed_file_count,
  modifies_tests,
  additions,
  deletions,
  construct_slugs_json,
  swe_bench_eligible,
  changed_file_paths_json,
  pr_narrative,
  pr_narrative_embedding_json,
  pr_narrative_version
) VALUES (
  (SELECT id FROM qualified_repos WHERE github_url = 'https://github.com/cloudflare/workers-sdk'),
  14150,
  'https://github.com/cloudflare/workers-sdk/pull/14150',
  '[wrangler] fix: send Workflows schedules as { cron } objects on deploy',
  '2026-06-02T08:14:32Z',
  NULL,
  3,
  1,
  17,
  5,
  '["typescript","wrangler","workflows","cron","deploy","tests"]',
  1,
  '[".changeset/fix-workflow-schedules-cron-mapping.md","packages/wrangler/src/__tests__/deploy/workflows.test.ts","packages/wrangler/src/triggers/deploy.ts"]',
  'The PR fixes Wrangler deploy schedule serialization for Workflows by sending schedule entries as { cron } objects and adds deploy regression coverage around scheduled workflows.',
  NULL,
  'source-backed-e2e-v1'
)
ON CONFLICT(repo_id, pr_number) DO UPDATE SET
  pr_url = excluded.pr_url,
  title = excluded.title,
  merged_at = excluded.merged_at,
  resolves_issue_number = excluded.resolves_issue_number,
  changed_file_count = excluded.changed_file_count,
  modifies_tests = excluded.modifies_tests,
  additions = excluded.additions,
  deletions = excluded.deletions,
  construct_slugs_json = excluded.construct_slugs_json,
  swe_bench_eligible = excluded.swe_bench_eligible,
  changed_file_paths_json = excluded.changed_file_paths_json,
  pr_narrative = excluded.pr_narrative,
  pr_narrative_embedding_json = excluded.pr_narrative_embedding_json,
  pr_narrative_version = excluded.pr_narrative_version;

INSERT INTO repo_sample_prs (
  repo_id,
  pr_number,
  pr_url,
  title,
  merged_at,
  resolves_issue_number,
  changed_file_count,
  modifies_tests,
  additions,
  deletions,
  construct_slugs_json,
  swe_bench_eligible,
  changed_file_paths_json,
  pr_narrative,
  pr_narrative_embedding_json,
  pr_narrative_version
) VALUES (
  (SELECT id FROM qualified_repos WHERE github_url = 'https://github.com/cloudflare/workers-sdk'),
  14435,
  'https://github.com/cloudflare/workers-sdk/pull/14435',
  '[Wrangler] Improve deploy warn for workflows with repeated names',
  '2026-06-26T10:51:43Z',
  NULL,
  4,
  1,
  NULL,
  NULL,
  '["typescript","wrangler","deploy","workflow-conflict-warning","vitest"]',
  1,
  '[".changeset/explain-workflow-name-conflict.md","packages/deploy-helpers/src/deploy/helpers/check-workflow-conflicts.ts","packages/wrangler/src/__tests__/deploy/check-workflow-conflicts.test.ts","packages/wrangler/src/__tests__/deploy/workflows.test.ts"]',
  'The PR improves Wrangler deploy warnings when Workflow names already belong to another Worker, adds uniqueness guidance, and updates unit/integration tests for the warning behavior.',
  NULL,
  'source-backed-e2e-v1'
)
ON CONFLICT(repo_id, pr_number) DO UPDATE SET
  pr_url = excluded.pr_url,
  title = excluded.title,
  merged_at = excluded.merged_at,
  resolves_issue_number = excluded.resolves_issue_number,
  changed_file_count = excluded.changed_file_count,
  modifies_tests = excluded.modifies_tests,
  additions = excluded.additions,
  deletions = excluded.deletions,
  construct_slugs_json = excluded.construct_slugs_json,
  swe_bench_eligible = excluded.swe_bench_eligible,
  changed_file_paths_json = excluded.changed_file_paths_json,
  pr_narrative = excluded.pr_narrative,
  pr_narrative_embedding_json = excluded.pr_narrative_embedding_json,
  pr_narrative_version = excluded.pr_narrative_version;
