/**
 * Role overlays — dimension weights + tag preferences per role family.
 *
 * The source of truth is `knowledge/culture/role-overlays/{slug}.md`. The
 * sync script `workers/api/scripts/sync-culture-wiki.ts` parses those markdown
 * files and regenerates the `ROLE_OVERLAYS` const below. Until the sync
 * script runs, the data here is hand-mirrored from the markdown.
 *
 * Workers don't have a filesystem, so the data must be bundled as a TS const.
 * Don't `fs.readFileSync` here — it will not work in the Worker runtime.
 */

import type { CompetencyDimension } from './cultureQuestionBank.js';

export type RoleOverlayId = 'senior-ic' | 'manager' | 'universal';

export interface RoleOverlay {
  id: RoleOverlayId;
  description: string;
  /** Multiplier (typically 1.0–1.4) applied to coverage-gap pressure per dimension. */
  weights: Record<CompetencyDimension, number>;
  preferredTags: string[];
  deprioritizedTags: string[];
}

// ─── Generated section — regenerated by sync-culture-wiki.ts ─────────────────

export const ROLE_OVERLAYS: Record<RoleOverlayId, RoleOverlay> = {
  'senior-ic': {
    id: 'senior-ic',
    description:
      'Senior individual contributor — expected to mentor and influence without formal authority, but not to manage people',
    weights: {
      ownership: 1.2,
      collaboration: 1.0,
      'learning-orientation': 1.3,
      'conflict-handling': 1.1,
      'self-awareness': 1.1,
    },
    preferredTags: [
      'technical-disagreement',
      'cross-team-influence',
      'mentorship-without-authority',
      'deep-debugging',
      'pattern-recognition',
    ],
    deprioritizedTags: ['direct-reports', 'performance-reviews', 'hiring-decisions', 'budget-ownership'],
  },
  manager: {
    id: 'manager',
    description: 'People manager (first-line) — responsible for direct reports, hiring, and performance',
    weights: {
      ownership: 1.0,
      collaboration: 1.2,
      'learning-orientation': 1.0,
      'conflict-handling': 1.4,
      'self-awareness': 1.3,
    },
    preferredTags: [
      'direct-reports',
      'performance-conversations',
      'hiring-decisions',
      'difficult-feedback',
      'team-health',
      'trade-off-decisions',
    ],
    deprioritizedTags: ['solo-deep-work', 'individual-technical-debugging'],
  },
  // `universal` is the no-op fallback used when no role-specific overlay applies.
  // Coverage-gap pressure flows through unchanged; all tags are neutral.
  universal: {
    id: 'universal',
    description: 'Default overlay applied when no role-specific overlay is selected',
    weights: {
      ownership: 1.0,
      collaboration: 1.0,
      'learning-orientation': 1.0,
      'conflict-handling': 1.0,
      'self-awareness': 1.0,
    },
    preferredTags: [],
    deprioritizedTags: [],
  },
};

// ─── Runtime API ─────────────────────────────────────────────────────────────

export function loadRoleOverlay(id: RoleOverlayId | null | undefined): RoleOverlay {
  if (!id) return ROLE_OVERLAYS.universal;
  return ROLE_OVERLAYS[id] ?? ROLE_OVERLAYS.universal;
}
