/**
 * Interview State Machine — Types
 *
 * Pure deterministic types for the role-discovery interview reducer.
 * No LLM references, no provider types. JSON-serializable everywhere.
 */

import type {
  RoleExchange,
  DomainCoverage,
  ConversationPhase,
  ParticipantRole,
  Domain,
} from '../../../types';

/** Column-by-column domain order (team first → why last). */
export const DOMAIN_COLUMN_ORDER: Domain[] = ['team', 'work', 'bar', 'codebase', 'process', 'why'];

/**
 * Domain question generation status.
 * Tracks where we are in the column-by-column flow.
 */
export type DomainCompletionStatus =
  | 'pending'      // not started
  | 'generating'   // waiting for LLM to produce questions
  | 'asking'       // asking the generated questions
  | 'depth_check'  // evaluating if 6 questions were enough
  | 'follow_up'    // asking 2-3 follow-ups
  | 'complete';    // done with this domain

/**
 * A question generated by the domain question generator.
 * Cached per-domain so we don't regen mid-column.
 */
export interface GeneratedQuestion {
  id: string;
  text: string;
  intent: string;
  /** Hints for the LLM on how to drill if the answer is thin. */
  drillingHints?: string[];
  /** What to ladder toward if energy is high. */
  ladderingTarget?: string;
}

/**
 * A pre-generated question sitting on the stack, ready to be served instantly.
 */
export interface QueuedQuestion {
  questionId: string;
  text: string;
  acknowledgment: string;
  goal?: string;
  expectedCoverage?: {
    domain: string;
    from: DomainCoverage;
    to: DomainCoverage;
  };
  probeAlignment?: string;
  questionType?: string;
  input: {
    type: 'text' | 'textarea' | 'tags' | 'select' | 'radio';
    options?: string[];
    placeholder?: string;
  };
  suggestedAnswers?: string[];
  knowledgeStateUpdate: Record<string, Record<string, unknown>>;
  domainCoverage: Record<string, DomainCoverage>;
}

/**
 * The full interview state. This is the single source of truth.
 * The UI holds this, the reducer transforms it, the generators read it.
 */
export interface InterviewState {
  // ── Static (set once at creation) ──
  baseline: Record<string, unknown>;
  participantRole: ParticipantRole | null;
  questionBudget: number;

  // ── Dynamic (mutated by reducer) ──
  exchanges: RoleExchange[];
  knowledgeState: Record<string, Record<string, unknown>>;
  coverage: Record<string, DomainCoverage>;
  phase: ConversationPhase;
  questionsAsked: number;
  synthesisReady: boolean;
  /** Why the current phase was selected (human-readable). */
  reasoning?: string;
  /** List of gaps that prevented synthesis (if any). */
  urgentGaps?: string[];
  /** Pre-generated questions — popped instantly without LLM latency. */
  questionStack: QueuedQuestion[];

  // ── NEW: Column-by-column domain tracking (Phase 1+) ──
  /** Which domain we're currently interviewing. Null before DISCOVERY starts. */
  currentDomain?: Domain | null;
  /** Per-domain completion status. */
  domainCompletion?: Record<string, DomainCompletionStatus>;
  /** Cached generated questions per domain (populated when entering 'asking'). */
  domainQuestions?: Record<string, GeneratedQuestion[]>;
  /** How many questions have been asked per domain so far. */
  domainQuestionsDelivered?: Record<string, number>;
  /** How many follow-up questions asked in the current domain (during follow_up phase). */
  domainFollowUpsDelivered?: number;
}

/**
 * Actions that drive the state machine. Every action is deterministic.
 */
export type InterviewAction =
  | {
      type: 'ANSWER';
      /** The user's answer text. */
      answer: string;
      /**
       * Optional knowledge-state update produced by the question generator
       * on the previous turn. When present, merged into state.knowledgeState
       * before phase re-computation.
       */
      knowledgeStateUpdate?: Record<string, Record<string, unknown>>;
      /**
       * Optional domain-coverage map produced by the question generator.
       * When present, written to state.coverage before phase re-computation.
       */
      domainCoverage?: Record<string, DomainCoverage>;
    }
  | { type: 'SKIP' }
  | { type: 'FORCE_SYNTHESIZE' }
  | {
      /** Cache domain questions produced by the domain generator. */
      type: 'CACHE_DOMAIN_QUESTIONS';
      domain: Domain;
      questions: GeneratedQuestion[];
    };

/**
 * Input needed to create the initial state for a participant.
 */
export interface CreateInterviewStateInput {
  baseline: Record<string, unknown>;
  participantRole: ParticipantRole | null;
  questionBudget: number;
  /** Optional seed knowledge from previous participants (multi-stakeholder). */
  seedKnowledgeState?: Record<string, Record<string, unknown>>;
}
