-- Migration: 0013_prompt_patches
-- Automated adaptive feedback loop for role-discovery question quality.
-- Stores generated patches and a corpus of bad questions for fuzzy matching.

CREATE TABLE IF NOT EXISTS prompt_patches (
  id                TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  rule_id           TEXT NOT NULL,
  participant_roles TEXT,              -- JSON array of roles, or null for all
  negative_example  TEXT NOT NULL,
  corrected_example TEXT NOT NULL,
  reason            TEXT NOT NULL,
  flag_count        INTEGER NOT NULL DEFAULT 1,
  auto_generated    INTEGER NOT NULL DEFAULT 0,  -- 1 = generated by feedback analyzer
  created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE IF NOT EXISTS bad_question_corpus (
  id                TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  question_text     TEXT NOT NULL,
  feedback          TEXT,
  participant_role  TEXT,
  rule_id           TEXT NOT NULL,
  patch_id          TEXT REFERENCES prompt_patches(id) ON DELETE SET NULL,
  embedding         TEXT,              -- JSON array of 1024 floats
  created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_pp_rule_id ON prompt_patches(rule_id);
CREATE INDEX IF NOT EXISTS idx_pp_flag_count ON prompt_patches(flag_count DESC);
CREATE INDEX IF NOT EXISTS idx_bqc_patch_id ON bad_question_corpus(patch_id);
CREATE INDEX IF NOT EXISTS idx_bqc_rule_id ON bad_question_corpus(rule_id);
CREATE INDEX IF NOT EXISTS idx_bqc_created_at ON bad_question_corpus(created_at);
