/**
 * Type definitions for codeReviewFollowUpAgent Lambda
 *
 * These types are self-contained — no imports from src/ to keep
 * the Lambda boundary clean.
 */

/**
 * A candidate annotation on a specific file/line in the code review diff.
 */
export interface CandidateAnnotation {
  fileIndex: number;
  lineNumber: number;
  severity: 'critical' | 'major' | 'minor';
  comment: string;
}

/**
 * The candidate's overall review verdict and summary.
 */
export interface ReviewSubmission {
  annotations: CandidateAnnotation[];
  verdict: 'approve' | 'request_changes' | 'comment';
  summary: string;
}

/**
 * A single follow-up question generated by the agent.
 */
export interface FollowUpQuestion {
  id: string;
  type: 'SHORT_ANSWER';
  question: string;
  /** Which part of the candidate's review this probes */
  context: string;
}

/**
 * Shape stored in Assessment.followUpQuestionsJson.
 */
export interface FollowUpQuestionsJson {
  questions: FollowUpQuestion[];
  answers: FollowUpAnswer[];
  generatedAt: string;
}

/**
 * A candidate's answer to a follow-up question.
 */
export interface FollowUpAnswer {
  questionId: string;
  answer: string;
  answeredAt: string;
}

/**
 * Input for the follow-up agent — received from AppSync mutation arguments.
 */
export interface FollowUpAgentInput {
  challengeSubmissionId: string;
}

/**
 * Raw ChallengeSubmission record from DynamoDB (only fields we need).
 * Named AssessmentRecord for backward compatibility with existing code references.
 */
export interface AssessmentRecord {
  id: string;
  challengeId?: string;
  assessmentId?: string;
  submission?: unknown;           // Raw JSON blob
  codeReviewAnnotations?: unknown;
  codeReviewSummary?: string;
}

/**
 * A single hunk line from cachedDiffJson.
 */
export interface DiffLine {
  type: 'context' | 'addition' | 'deletion';
  lineNumber: number;
  content: string;
}

/**
 * A single hunk from cachedDiffJson.
 */
export interface DiffHunk {
  header: string;
  lines: DiffLine[];
}

/**
 * A single file entry from cachedDiffJson.
 */
export interface DiffFile {
  path: string;
  status: string;
  additions: number;
  deletions: number;
  hunks: DiffHunk[];
}

/**
 * The structured diff stored in Challenge.cachedDiffJson.
 */
export interface CachedDiffJson {
  files: DiffFile[];
}

/**
 * Raw Challenge record from DynamoDB (only fields we need).
 */
export interface ChallengeRecord {
  id: string;
  type?: string;
  title?: string;
  instructions?: string;
  serverConfig?: unknown;         // Contains ground truth, diff context
  config?: unknown;               // Public config
  cachedDiffJson?: unknown;       // Structured diff: { files: [...] }
  githubPrTitle?: string;
  githubPrDescription?: string;
}

/**
 * Output returned by the Lambda / AppSync mutation.
 */
export interface FollowUpAgentOutput {
  questions: FollowUpQuestion[];
  costTracking: {
    sessionCost: number;
    remainingBudget: number;
    callCount: number;
  };
  processingTime: number;
}

/**
 * The structure the model returns for the questions.
 */
export interface ModelQuestionsOutput {
  questions: Array<{
    id: string;
    question: string;
    context: string;
  }>;
}
