/**
 * Type definitions for codeReviewFollowUpAgent Lambda
 *
 * These types are self-contained — no imports from src/ to keep
 * the Lambda boundary clean.
 */

/**
 * A candidate annotation on a specific file/line in the code review diff.
 */
export interface CandidateAnnotation {
  fileIndex: number;
  lineNumber: number;
  severity: 'critical' | 'major' | 'minor';
  comment: string;
}

/**
 * The candidate's overall review verdict and summary.
 */
export interface ReviewSubmission {
  annotations: CandidateAnnotation[];
  verdict: 'approve' | 'request_changes' | 'comment';
  summary: string;
}

/**
 * A single follow-up question generated by the agent.
 */
export interface FollowUpQuestion {
  id: string;
  type: 'SHORT_ANSWER';
  question: string;
  /** Which part of the candidate's review this probes */
  context: string;
}

/**
 * Shape stored in Assessment.followUpQuestionsJson.
 */
export interface FollowUpQuestionsJson {
  questions: FollowUpQuestion[];
  answers: FollowUpAnswer[];
  generatedAt: string;
}

/**
 * A candidate's answer to a follow-up question.
 */
export interface FollowUpAnswer {
  questionId: string;
  answer: string;
  answeredAt: string;
}

/**
 * Input for the follow-up agent — received from AppSync mutation arguments.
 */
export interface FollowUpAgentInput {
  assessmentId: string;
}

/**
 * Raw Assessment record from DynamoDB (only fields we need).
 */
export interface AssessmentRecord {
  id: string;
  challengeId?: string;
  submission?: unknown;           // Raw JSON blob
  codeReviewAnnotations?: unknown;
  codeReviewSummary?: string;
}

/**
 * Raw Challenge record from DynamoDB (only fields we need).
 */
export interface ChallengeRecord {
  id: string;
  type?: string;
  title?: string;
  instructions?: string;
  serverConfig?: unknown;         // Contains ground truth, diff context
  config?: unknown;               // Public config
}

/**
 * Output returned by the Lambda / AppSync mutation.
 */
export interface FollowUpAgentOutput {
  questions: FollowUpQuestion[];
  costTracking: {
    sessionCost: number;
    remainingBudget: number;
    callCount: number;
  };
  processingTime: number;
}

/**
 * The structure Claude returns for the questions.
 */
export interface ClaudeQuestionsOutput {
  questions: Array<{
    id: string;
    question: string;
    context: string;
  }>;
}
